-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    "UserId" bigint NOT NULL,
    "Username" character varying(30) NOT NULL,
    "Password" character varying(100) NOT NULL,
    "Fullname" character varying(150) NOT NULL,
    "CreatedDate" date NOT NULL,
    "CreatedBy" character varying(150),
    "UpdatedDate" date,
    "UpdatedBy" character varying(150),
    PRIMARY KEY ("UserId")
);

CREATE TABLE IF NOT EXISTS public.usertokens
(
    "UserId" bigint NOT NULL,
    "JwtToken" text NOT NULL,
    "RefreshToken" text NOT NULL,
    "ExpiredToken" bigint NOT NULL,
    "ExpiredRefreshToken" bigint NOT NULL,
    "CreatedDate" date NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE IF NOT EXISTS public.logerrors
(
    "Id" bigserial NOT NULL,
    "UserId" bigint NOT NULL,
    "ModuleName" character varying(255),
    "DescError" text,
    "CreatedDate" date NOT NULL,
    PRIMARY KEY ("Id")
);
END;